/**
 * TEMPORARY placeholder photo set for the scatter home.
 *
 * These 24 entries are NOT real gallery data. Every variant leaf points at a
 * single local placeholder file (`/placeholders/demo-NN.jpg`); only the pixel
 * dimensions are meaningful (they drive aspect-ratio-dependent layout math).
 * Replace this module with real ingested photos once the pipeline delivers them.
 *
 * Everything here is deterministic (no Math.random / Date.now) so SSR and CSR
 * produce identical layouts.
 */

import type { Photo, PhotoFormat, PhotoVariants } from '$lib/types/index.js';
import { getImageUrl } from '$lib/config/r2.js';

/** Shared deterministic seed for demo-driven layout + intro logic. */
export const DEMO_SEED = 20260801;

/**
 * Resolve an image `url` to a loadable source. Placeholder/static paths begin
 * with `/` and are returned untouched; everything else is treated as an R2 key
 * and prefixed with the configured public bucket URL.
 *
 * @param url Placeholder path (starts with `/`) or R2 object key.
 * @returns A URL usable directly in `src`/`href`.
 */
export function photoSrc(url: string): string {
	return url.startsWith('/') ? url : getImageUrl(url);
}

/**
 * Intrinsic pixel dimensions `[width, height]` for demo-01..demo-24, in order.
 * Kept as a compact table so the entries below can be generated by a mapper
 * rather than hand-duplicated.
 */
const DEMO_DIMENSIONS: readonly (readonly [number, number])[] = [
	[900, 1350], // 01
	[1200, 800], // 02
	[960, 1200], // 03
	[1200, 750], // 04
	[1000, 1000], // 05
	[900, 1350], // 06
	[1200, 800], // 07
	[960, 1200], // 08
	[1200, 900], // 09
	[900, 1350], // 10
	[1200, 800], // 11
	[1000, 1250], // 12
	[1200, 675], // 13
	[900, 1350], // 14
	[1200, 800], // 15
	[1000, 1000], // 16
	[960, 1200], // 17
	[1200, 900], // 18
	[900, 1350], // 19
	[1200, 800], // 20
	[960, 1200], // 21
	[1200, 750], // 22
	[900, 1350], // 23
	[1200, 800] // 24
];

/** Zero-pad a positive integer to two digits (1 -> "01"). */
function pad2(n: number): string {
	return String(n).padStart(2, '0');
}

/**
 * Build a full set of variants where every size/format leaf points at the same
 * placeholder `file` and reports the same intrinsic dimensions. Fresh objects
 * per leaf avoid accidental reference aliasing.
 */
function demoVariants(file: string, width: number, height: number): PhotoVariants {
	const leaf = (): PhotoFormat => ({ url: file, width, height });
	const group = () => ({ avif: leaf(), webp: leaf(), jpg: leaf() });
	return {
		thumb: group(),
		medium: group(),
		large: group(),
		original: group()
	};
}

/**
 * TEMPORARY demo photo set — exactly 24 entries (`demo-01`..`demo-24`).
 * Generated from {@link DEMO_DIMENSIONS}; replace with real ingested photos.
 */
export const demoPhotos: Photo[] = DEMO_DIMENSIONS.map(([width, height], i) => {
	const nn = pad2(i + 1);
	const file = `/placeholders/demo-${nn}.jpg`;
	// Deterministic staggered timestamps: 2026-07-01 + (i + 1) days => 2026-07-02..2026-07-25.
	const stamp = `2026-07-${pad2(i + 2)}T12:00:00.000Z`;
	return {
		id: `demo-${nn}`,
		slug: `demo-${nn}`,
		title: `Frame ${nn}`,
		tags: [],
		collectionIds: [],
		featured: false,
		aspectRatio: width / height,
		variants: demoVariants(file, width, height),
		exif: {},
		createdAt: stamp,
		updatedAt: stamp
	};
});
